### ISSUE TITLE
ESC bug in TodoMVC jQuery

### ISSUE THREAD

**Issue by gordonmzhu** [gordonmzhu/beasts#5]
Write the code that fixes the problem Luca describes in his [pull request](https://github.com/tastejs/todomvc/pull/1737). Don't peek at Luca's solution until you're done. 

You should [fork](https://help.github.com/articles/fork-a-repo/) my repo, which will copy it to your Github account. You can then make the code changes right from the Github website by [following these steps](https://help.github.com/articles/editing-files-in-your-repository/).

Once you've made the change, share a link to your repository in a comment below.

Thanks @luc4leone for spotting this :)

**Comment by naterino** [comment]
Here is my updated repo.

Repo:
https://github.com/naterino/todomvc

File:
https://github.com/naterino/todomvc/blob/master/examples/jquery/js/app.js

**Comment by tiffwu** [comment]
Here's my fix: https://github.com/tiffwu/todomvc/commit/1eab546556c671dccb57c3f266b744b68e789c99?diff=split

**Comment by bpaysen** [comment]
Here is my repo for TodoMVC: 
https://github.com/bpaysen/todomvc

Changes in this file: https://github.com/bpaysen/todomvc/blob/3080f59fb831b23d132272067926f5257f598796/examples/jquery/js/app.js

**Comment by jjsquillante** [comment]
@naterino  well done, nate. After completing mine, and looking around - it looks like we had the same thought process on this.
Changes: 
https://github.com/tastejs/todomvc/commit/55e338fae6b5a9027516b0bb1228b94308eb90f1

**Comment by IvoVermeer** [comment]
My solution is in this [commit](https://github.com/IvoVermeer/todomvc-1/commit/a5499506d4588c62d8f143c6a68c2daa092bfe04).

**Comment by hanihsdd** [comment]
Here's my commit:
https://github.com/hanihsdd/todomvc/commit/a420cce14eda17b34de9f6573380395fb30c10be

Great job @luc4leone for spotting this

**Comment by michael-mafi** [comment]
https://gist.github.com/michael-mafi/658c06748e8ba0dc9f74b49bd3af429b
🎬

**Comment by thomaspatricksteven** [comment]
Here's my [update](https://github.com/thomaspatricksteven/todomvc/commit/2aa90fd3727b5f77ae1c1e9e030234296a37b05c#diff-db003fe9ad30fbb1c492d01db28886f8).

I spent a lot of time trying to figure out exactly how the Jquery data method works. That time was mostly wasted. Haha.

**Comment by kennyklee** [comment]
Here is mine. :)

https://github.com/kennyklee/todomvc/commit/20da54583d79a6d62759c2e9d65aa6940abf299c

**Comment by forral** [comment]
my file:
https://github.com/forral/todomvc/blob/master/examples/jquery/js/app.js

my repo:
https://github.com/forral/todomvc

**Comment by benhbaik** [comment]
https://github.com/benhbaik/todomvc/pull/1/commits/0dd14eb8aca4df3f383deb061fd1516bf60fc151

**Comment by benhbaik** [comment]
https://github.com/benhbaik/todomvc/commit/df1c7749285663734d287a774564eddd4766a4b7
Pressing enter on empty edit input issue.

**Comment by gustavlrsn** [comment]
Here's my commit: https://github.com/gustavlrsn/todomvc/commit/c6f492a942c94e90bb99528644647ede62b0a85b

**Comment by anthonyponzio1992** [comment]
Short fix for this one https://github.com/anthonyponzio1992/todomvc/commit/73058cdd587da4d347395a21ffd126d000fec05d

**Comment by jasonpberry** [comment]
Mine (1st attempt) :  https://github.com/jasonpberry/everything-practical-javascript/blob/master/Beasts/Challenge-2/js/app.js#L176

**Comment by peterawlings** [comment]
https://github.com/gordonmzhu/todomvc/compare/master...peterawlings:master

**Comment by meekowhy** [comment]
https://github.com/meekowhy/todomvc-1/blob/master/examples/jquery/js/app.js

**Comment by sindreon** [comment]
repo: https://github.com/sindreon/todomvc

commit: https://github.com/sindreon/todomvc/commit/3c1025e97173ca2bd3d137c1b5838323e101a5a0

line: https://github.com/sindreon/todomvc/blob/master/examples/jquery/js/app.js#L168

**Comment by gordonmzhu** [comment]
Retiring this problem because it's been difficult to verify the quality of different submissions. This is because the UI specs for TodoMVC are not well-defined. Not a big deal because we'll likely look into more subtle specific UI issues like this one later on in the curriculum.
